id = "vhdl"
name = "VHDL"
version = "0.0.2"
schema_version = 1
authors = ["Matthieu Michon <matthieu.michon@gmail.com>"]
description = "VHDL support"
languages = ["languages/vhdl"]

[grammars.vhdl]
repository = "https://github.com/alemuller/tree-sitter-vhdl"
commit = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5"
